language: clojure
lein: lein
before_install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.394.sh
  - chmod +x linux-install-1.9.0.394.sh
  - sudo ./linux-install-1.9.0.394.sh
script:
  - lein test
  - lein run -m metaprob.examples.main test
